# Generated by Django 5.1.3 on 2026-05-08 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ad')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='təsvir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaradılıb')),
            ],
            options={
                'verbose_name': 'kateqoriya',
                'verbose_name_plural': 'kateqoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ad')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='təsvir')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='qiymət')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='ehtiyat')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SKU')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaradılıb')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yenilənib')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='kateqoriya')),
            ],
            options={
                'verbose_name': 'məhsul',
                'verbose_name_plural': 'məhsullar',
                'ordering': ['-created_at'],
            },
        ),
    ]
