# Fayl adı: shop (sites-available içində tam yol: /etc/nginx/sites-available/shop)
# Əvvəl aşağıdakı yolları öz serverinizə uyğun dəyişin: /var/www/lesson

server {
    listen 324;
    listen [::]:324;
    server_name 178.104.92.41;

    client_max_body_size 25m;

    root /var/www/lesson/frontend/dist;

    location /static/ {
        alias /var/www/lesson/backend/staticfiles/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public";
    }

    location /api/ {
        proxy_pass http://127.0.0.1:325;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location /admin/ {
        proxy_pass http://127.0.0.1:325;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
